spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/soa
    driver-class-name: org.postgresql.Driver
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      default-media-type: application/xml
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: true

server:
  port: 8081
